# Test getting fastf1 telemetry data for specific driver, etc
GET http://localhost:3000/api/telemetry/fetch?year=2022&track=Monza&session=Q&driver=LEC
Content-Type: application/json

###
# Test registering a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Mike",
    "password": "Guazouski?"
}

###
# Test loging in as a user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Mike",
    "password": "Guazouski?"
}

###
# Test deleting a user. Requires bearer token. The correct token is obtainable via sign in
DELETE http://localhost:3000/api/auth/delete_account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJ1c2VybmFtZSI6Ik1pa2UiLCJleHAiOjE3MzgxMzc5NzZ9.VKpCh02lzlQ_wqh3uxc-n4ZdvUdSTNITQ9dsSK52ge4
Content-Type: application/json

{
    "username": "Mike",
    "password": "Guazouski?"
}