###
# WORKING Test registering a new user
POST https://seng401-telemetryproject-d3hw.onrender.com/api/auth/register
Content-Type: application/json

{
    "username": "Mike@test.com",
    "password": "Guazouski?"
}

###
# WORKING Test loging in as a user

POST https://seng401-telemetryproject-d3hw.onrender.com/api/auth/login
Content-Type: application/json

{
    "username": "Mike@test.com",
    "password": "Guazouski?"
}

###
# WORKING Test deleting a user. Requires bearer token. The correct token is obtainable via sign in
DELETE https://seng401-telemetryproject-d3hw.onrender.com/api/auth/delete_account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJ1c2VybmFtZSI6Ik1pa2UiLCJleHAiOjE3MzgxMzc5NzZ9.VKpCh02lzlQ_wqh3uxc-n4ZdvUdSTNITQ9dsSK52ge4
Content-Type: application/json

{
    "username": "Mike@test.com",
    "password": "Guazouski?"
}
